import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import AuthenticationProvider from "@/contexts/AuthenticationManager/Provider";

const poppins = Roboto({
  weight: "700",
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meus Leads",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <AuthenticationProvider>{children}</AuthenticationProvider>
      </body>
    </html>
  );
}
